version: '3.8'

services:
  app:
    container_name: testapp
    build: .
    command: bash -c "/app/runserver.sh"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
