version: '3.8'

services:
  app:
    container_name: testapp
    build: .
    command: bash -c "/app/runserver.sh"
    restart: always
    volumes:
      - .:/app
    networks:
      - default

  nginx:
      image: nginx:latest
      container_name: ngx
      ports:
        - "80:80"
      volumes:
        - ./nginx:/etc/nginx/conf.d
      depends_on:
        - app
networks:
  default:
      name: payme_india_network
