version: '3.8'

services:
  app:
    container_name: testapp
    build: .
    command: bash -c "/app/runserver.sh"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: testdb
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    restart: always
    ports:
      - 5433:5432

volumes:
  postgres_data:
