version: '3.8'

services:
  app:
    stdin_open: true
    tty: true
    depends_on:
      - db
    networks:
      - default

  db:
    container_name: testdb
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TEST=test
    env_file:
      - ./.env
    restart: always
    ports:
      - 5433:5432
    networks:
      - default

volumes:
  postgres_data:
